package com.admin.rr.entity;
// Generated Nov 6, 2018 3:45:49 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrBrandMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_BRAND_MASTER")
public class RrBrandMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrBrandMasterId;
	private String brandName;
	private String status;
	private Set<RrOrder> rrOrders = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_BRAND_MASTER_ID", unique = true, nullable = false)
	public Long getRrBrandMasterId() {
		return this.rrBrandMasterId;
	}

	public void setRrBrandMasterId(Long rrBrandMasterId) {
		this.rrBrandMasterId = rrBrandMasterId;
	}

	@Column(name = "BRAND_NAME", nullable = false, length = 100)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrBrandMaster")
	public Set<RrOrder> getRrOrders() {
		return this.rrOrders;
	}

	public void setRrOrders(Set<RrOrder> rrOrders) {
		this.rrOrders = rrOrders;
	}

}
