package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrCountryMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_COUNTRY_MASTER", uniqueConstraints = { @UniqueConstraint(columnNames = "COUNTRY_CODE"),
		@UniqueConstraint(columnNames = "ISD_CODE"), @UniqueConstraint(columnNames = "CURRENCY_CODE") })
public class RrCountryMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrCountryMasterId;
	private String countryCode;
	private String countryName;
	private String isdCode;
	private String currencyCode;
	private String currencyName;
	private String status;
	private Set<RrOrganizationMaster> rrOrganizationMasters = new HashSet<>(0);
	private Set<RrStateMaster> rrStateMasters = new HashSet<>(0);
	private Set<RrUserProfile> rrUserProfiles = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_COUNTRY_MASTER_ID", unique = true, nullable = false)
	public Long getRrCountryMasterId() {
		return this.rrCountryMasterId;
	}

	public void setRrCountryMasterId(Long rrCountryMasterId) {
		this.rrCountryMasterId = rrCountryMasterId;
	}

	@Column(name = "COUNTRY_CODE", unique = true, nullable = false, length = 5)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "COUNTRY_NAME", nullable = false, length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "ISD_CODE", unique = true, nullable = false, length = 5)
	public String getIsdCode() {
		return this.isdCode;
	}

	public void setIsdCode(String isdCode) {
		this.isdCode = isdCode;
	}

	@Column(name = "CURRENCY_CODE", unique = true, nullable = false, length = 5)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "CURRENCY_NAME", length = 50)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrCountryMaster")
	public Set<RrOrganizationMaster> getRrOrganizationMasters() {
		return this.rrOrganizationMasters;
	}

	public void setRrOrganizationMasters(Set<RrOrganizationMaster> rrOrganizationMasters) {
		this.rrOrganizationMasters = rrOrganizationMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrCountryMaster")
	public Set<RrStateMaster> getRrStateMasters() {
		return this.rrStateMasters;
	}

	public void setRrStateMasters(Set<RrStateMaster> rrStateMasters) {
		this.rrStateMasters = rrStateMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrCountryMaster")
	public Set<RrUserProfile> getRrUserProfiles() {
		return this.rrUserProfiles;
	}

	public void setRrUserProfiles(Set<RrUserProfile> rrUserProfiles) {
		this.rrUserProfiles = rrUserProfiles;
	}

}
