package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrInvoice generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_INVOICE")
public class RrInvoice extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrInvoiceId;
	private RrOrder rrOrder;
	private String paidAmount;
	private String pendingAmount;
	private String totalAmount;
	private String particulars;
	private String paymentStatus;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_INVOICE_ID", unique = true, nullable = false)
	public Long getRrInvoiceId() {
		return this.rrInvoiceId;
	}

	public void setRrInvoiceId(Long rrInvoiceId) {
		this.rrInvoiceId = rrInvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_ORDER_ID", nullable = false)
	public RrOrder getRrOrder() {
		return this.rrOrder;
	}

	public void setRrOrder(RrOrder rrOrder) {
		this.rrOrder = rrOrder;
	}

	@Column(name = "PAID_AMOUNT", nullable = false)
	public String getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(String paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Column(name = "PENDING_AMOUNT", nullable = false)
	public String getPendingAmount() {
		return this.pendingAmount;
	}

	public void setPendingAmount(String pendingAmount) {
		this.pendingAmount = pendingAmount;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false)
	public String getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(String totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "PARTICULARS")
	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	@Column(name = "PAYMENT_STATUS", nullable = false, length = 8)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

}
