package com.admin.rr.entity;
// Generated Nov 7, 2018 11:45:06 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RrIssueMaster generated by hbm2java
 */
@Entity
@Table(name = "RR_ISSUE_MASTER")
public class RrIssueMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrIssueMasterId;
	private String issueName;
	private String status;
	private Set<RrOrder> rrOrders = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_ISSUE_MASTER_ID", unique = true, nullable = false)
	public Long getRrIssueMasterId() {
		return this.rrIssueMasterId;
	}

	public void setRrIssueMasterId(Long rrIssueMasterId) {
		this.rrIssueMasterId = rrIssueMasterId;
	}

	@Column(name = "ISSUE_NAME", nullable = false)
	public String getIssueName() {
		return this.issueName;
	}

	public void setIssueName(String issueName) {
		this.issueName = issueName;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrIssueMaster")
	public Set<RrOrder> getRrOrders() {
		return this.rrOrders;
	}

	public void setRrOrders(Set<RrOrder> rrOrders) {
		this.rrOrders = rrOrders;
	}

}
