package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrOrganizationMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_ORGANIZATION_MASTER", uniqueConstraints = @UniqueConstraint(columnNames = "ORGANIZATION_CODE"))
public class RrOrganizationMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrOrganizationMasterId;
	private RrCountryMaster rrCountryMaster;
	private RrStateMaster rrStateMaster;
	private String organizationLogo;
	private String organizationCode;
	private String organizationName;
	private String organizationDescription;
	private String telephoneNo;
	private String mobileNo;
	private String organizationAddr1;
	private String organizationAddr2;
	private String organizationAddr3;
	private String district;
	private String pincode;
	private String status;
	private Set<RrUserProfile> rrUserProfiles = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_ORGANIZATION_MASTER_ID", unique = true, nullable = false)
	public Long getRrOrganizationMasterId() {
		return this.rrOrganizationMasterId;
	}

	public void setRrOrganizationMasterId(Long rrOrganizationMasterId) {
		this.rrOrganizationMasterId = rrOrganizationMasterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_COUNTRY_MASTER_ID", nullable = false)
	public RrCountryMaster getRrCountryMaster() {
		return this.rrCountryMaster;
	}

	public void setRrCountryMaster(RrCountryMaster rrCountryMaster) {
		this.rrCountryMaster = rrCountryMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_STATE_MASTER_ID", nullable = false)
	public RrStateMaster getRrStateMaster() {
		return this.rrStateMaster;
	}

	public void setRrStateMaster(RrStateMaster rrStateMaster) {
		this.rrStateMaster = rrStateMaster;
	}

	@Column(name = "ORGANIZATION_LOGO")
	public String getOrganizationLogo() {
		return this.organizationLogo;
	}

	public void setOrganizationLogo(String organizationLogo) {
		this.organizationLogo = organizationLogo;
	}

	@Column(name = "ORGANIZATION_CODE", unique = true, nullable = false, length = 50)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "ORGANIZATION_NAME", nullable = false)
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Column(name = "ORGANIZATION_DESCRIPTION")
	public String getOrganizationDescription() {
		return this.organizationDescription;
	}

	public void setOrganizationDescription(String organizationDescription) {
		this.organizationDescription = organizationDescription;
	}

	@Column(name = "TELEPHONE_NO", length = 20)
	public String getTelephoneNo() {
		return this.telephoneNo;
	}

	public void setTelephoneNo(String telephoneNo) {
		this.telephoneNo = telephoneNo;
	}

	@Column(name = "MOBILE_NO", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "ORGANIZATION_ADDR1", nullable = false)
	public String getOrganizationAddr1() {
		return this.organizationAddr1;
	}

	public void setOrganizationAddr1(String organizationAddr1) {
		this.organizationAddr1 = organizationAddr1;
	}

	@Column(name = "ORGANIZATION_ADDR2", nullable = false)
	public String getOrganizationAddr2() {
		return this.organizationAddr2;
	}

	public void setOrganizationAddr2(String organizationAddr2) {
		this.organizationAddr2 = organizationAddr2;
	}

	@Column(name = "ORGANIZATION_ADDR3", nullable = false)
	public String getOrganizationAddr3() {
		return this.organizationAddr3;
	}

	public void setOrganizationAddr3(String organizationAddr3) {
		this.organizationAddr3 = organizationAddr3;
	}

	@Column(name = "DISTRICT", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "PINCODE", nullable = false, length = 50)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrOrganizationMaster")
	public Set<RrUserProfile> getRrUserProfiles() {
		return this.rrUserProfiles;
	}

	public void setRrUserProfiles(Set<RrUserProfile> rrUserProfiles) {
		this.rrUserProfiles = rrUserProfiles;
	}

}
