package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrPermissionMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_PERMISSION_MASTER")
public class RrPermissionMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrPermissionMasterId;
	private RrMenus rrMenus;
	private RrUserRoleMaster rrUserRoleMaster;
	private byte isViewYes;
	private byte isAddYes;
	private byte isEditYes;
	private byte isDeleteYes;
	private byte isApproveYes;
	private byte isUploadYes;
	private byte isDownloadYes;
	private String status;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_PERMISSION_MASTER_ID", unique = true, nullable = false)
	public Long getRrPermissionMasterId() {
		return this.rrPermissionMasterId;
	}

	public void setRrPermissionMasterId(Long rrPermissionMasterId) {
		this.rrPermissionMasterId = rrPermissionMasterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_MENUS_ID", nullable = false)
	public RrMenus getRrMenus() {
		return this.rrMenus;
	}

	public void setRrMenus(RrMenus rrMenus) {
		this.rrMenus = rrMenus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_USER_ROLE_MASTER_ID", nullable = false)
	public RrUserRoleMaster getRrUserRoleMaster() {
		return this.rrUserRoleMaster;
	}

	public void setRrUserRoleMaster(RrUserRoleMaster rrUserRoleMaster) {
		this.rrUserRoleMaster = rrUserRoleMaster;
	}

	@Column(name = "IS_VIEW_YES", nullable = false)
	public byte getIsViewYes() {
		return this.isViewYes;
	}

	public void setIsViewYes(byte isViewYes) {
		this.isViewYes = isViewYes;
	}

	@Column(name = "IS_ADD_YES", nullable = false)
	public byte getIsAddYes() {
		return this.isAddYes;
	}

	public void setIsAddYes(byte isAddYes) {
		this.isAddYes = isAddYes;
	}

	@Column(name = "IS_EDIT_YES", nullable = false)
	public byte getIsEditYes() {
		return this.isEditYes;
	}

	public void setIsEditYes(byte isEditYes) {
		this.isEditYes = isEditYes;
	}

	@Column(name = "IS_DELETE_YES", nullable = false)
	public byte getIsDeleteYes() {
		return this.isDeleteYes;
	}

	public void setIsDeleteYes(byte isDeleteYes) {
		this.isDeleteYes = isDeleteYes;
	}

	@Column(name = "IS_APPROVE_YES", nullable = false)
	public byte getIsApproveYes() {
		return this.isApproveYes;
	}

	public void setIsApproveYes(byte isApproveYes) {
		this.isApproveYes = isApproveYes;
	}

	@Column(name = "IS_UPLOAD_YES", nullable = false)
	public byte getIsUploadYes() {
		return this.isUploadYes;
	}

	public void setIsUploadYes(byte isUploadYes) {
		this.isUploadYes = isUploadYes;
	}

	@Column(name = "IS_DOWNLOAD_YES", nullable = false)
	public byte getIsDownloadYes() {
		return this.isDownloadYes;
	}

	public void setIsDownloadYes(byte isDownloadYes) {
		this.isDownloadYes = isDownloadYes;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
