package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrStateMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_STATE_MASTER", uniqueConstraints = @UniqueConstraint(columnNames = "STATE_CODE"))
public class RrStateMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrStateMasterId;
	private RrCountryMaster rrCountryMaster;
	private String stdCode;
	private String stateCode;
	private String stateName;
	private String status;
	private Set<RrUserProfile> rrUserProfiles = new HashSet<>(0);
	private Set<RrOrganizationMaster> rrOrganizationMasters = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_STATE_MASTER_ID", unique = true, nullable = false)
	public Long getRrStateMasterId() {
		return this.rrStateMasterId;
	}

	public void setRrStateMasterId(Long rrStateMasterId) {
		this.rrStateMasterId = rrStateMasterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_COUNTRY_MASTER_ID", nullable = false)
	public RrCountryMaster getRrCountryMaster() {
		return this.rrCountryMaster;
	}

	public void setRrCountryMaster(RrCountryMaster rrCountryMaster) {
		this.rrCountryMaster = rrCountryMaster;
	}

	@Column(name = "STD_CODE", length = 15)
	public String getStdCode() {
		return this.stdCode;
	}

	public void setStdCode(String stdCode) {
		this.stdCode = stdCode;
	}

	@Column(name = "STATE_CODE", unique = true, nullable = false)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "STATE_NAME", nullable = false, length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrStateMaster")
	public Set<RrUserProfile> getRrUserProfiles() {
		return this.rrUserProfiles;
	}

	public void setRrUserProfiles(Set<RrUserProfile> rrUserProfiles) {
		this.rrUserProfiles = rrUserProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrStateMaster")
	public Set<RrOrganizationMaster> getRrOrganizationMasters() {
		return this.rrOrganizationMasters;
	}

	public void setRrOrganizationMasters(Set<RrOrganizationMaster> rrOrganizationMasters) {
		this.rrOrganizationMasters = rrOrganizationMasters;
	}

}
