package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrUserRoleMaster generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_USER_ROLE_MASTER")
public class RrUserRoleMaster extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrUserRoleMasterId;
	private String roleName;
	private String roleDesc;
	private String userType;
	private String status;
	private Set<RrUserProfile> rrUserProfiles = new HashSet<>(0);
	private Set<RrPermissionMaster> rrPermissionMasters = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_USER_ROLE_MASTER_ID", unique = true, nullable = false)
	public Long getRrUserRoleMasterId() {
		return this.rrUserRoleMasterId;
	}

	public void setRrUserRoleMasterId(Long rrUserRoleMasterId) {
		this.rrUserRoleMasterId = rrUserRoleMasterId;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 30)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_DESC", nullable = false, length = 80)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 12)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrUserRoleMaster")
	public Set<RrUserProfile> getRrUserProfiles() {
		return this.rrUserProfiles;
	}

	public void setRrUserProfiles(Set<RrUserProfile> rrUserProfiles) {
		this.rrUserProfiles = rrUserProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrUserRoleMaster")
	public Set<RrPermissionMaster> getRrPermissionMasters() {
		return this.rrPermissionMasters;
	}

	public void setRrPermissionMasters(Set<RrPermissionMaster> rrPermissionMasters) {
		this.rrPermissionMasters = rrPermissionMasters;
	}

}
