package com.admin.rr.entity;
// Generated Nov 4, 2018 2:06:54 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * RrUserProfile generated by hbm2java
 */
@Entity
@DynamicUpdate(value = true)
@SelectBeforeUpdate(value = true)
@Table(name = "RR_USER_PROFILE", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NAME"))
public class RrUserProfile extends BaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rrUserProfileId;
	private RrCountryMaster rrCountryMaster;
	private RrOrganizationMaster rrOrganizationMaster;
	private RrStateMaster rrStateMaster;
	private RrUserRoleMaster rrUserRoleMaster;
	private String userName;
	private String userPwrd;
	private String userTitle;
	private String gender;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String mobile;
	private Date dob;
	private String profilePhotoImg;
	private String voterIdNo;
	private String voterIdImg;
	private String adharCardNo;
	private String adharCardImg;
	private Date dateOfJoining;
	private String permanentAddr1;
	private String permanentAddr2;
	private String permanentAddr3;
	private String presentAddr1;
	private String presentAddr2;
	private String presentAddr3;
	private Date lastLoginTime;
	private String status;
	private Set<RrOrder> rrOrders = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RR_USER_PROFILE_ID", unique = true, nullable = false)
	public Long getRrUserProfileId() {
		return this.rrUserProfileId;
	}

	public void setRrUserProfileId(Long rrUserProfileId) {
		this.rrUserProfileId = rrUserProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_COUNTRY_MASTER_ID", nullable = false)
	public RrCountryMaster getRrCountryMaster() {
		return this.rrCountryMaster;
	}

	public void setRrCountryMaster(RrCountryMaster rrCountryMaster) {
		this.rrCountryMaster = rrCountryMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_ORGANIZATION_MASTER_ID", nullable = false)
	public RrOrganizationMaster getRrOrganizationMaster() {
		return this.rrOrganizationMaster;
	}

	public void setRrOrganizationMaster(RrOrganizationMaster rrOrganizationMaster) {
		this.rrOrganizationMaster = rrOrganizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_STATE_MASTER_ID", nullable = false)
	public RrStateMaster getRrStateMaster() {
		return this.rrStateMaster;
	}

	public void setRrStateMaster(RrStateMaster rrStateMaster) {
		this.rrStateMaster = rrStateMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RR_USER_ROLE_MASTER_ID", nullable = false)
	public RrUserRoleMaster getRrUserRoleMaster() {
		return this.rrUserRoleMaster;
	}

	public void setRrUserRoleMaster(RrUserRoleMaster rrUserRoleMaster) {
		this.rrUserRoleMaster = rrUserRoleMaster;
	}

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_PWD", nullable = false)
	public String getUserPwrd() {
		return this.userPwrd;
	}

	public void setUserPwrd(String userPwrd) {
		this.userPwrd = userPwrd;
	}

	@Column(name = "USER_TITLE", nullable = false, length = 8)
	public String getUserTitle() {
		return this.userTitle;
	}

	public void setUserTitle(String userTitle) {
		this.userTitle = userTitle;
	}

	@Column(name = "GENDER", nullable = false, length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME", length = 30)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MOBILE", nullable = false, length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "PROFILE_PHOTO_IMG", length = 250)
	public String getProfilePhotoImg() {
		return this.profilePhotoImg;
	}

	public void setProfilePhotoImg(String profilePhotoImg) {
		this.profilePhotoImg = profilePhotoImg;
	}

	@Column(name = "VOTER_ID_NO", nullable = false, length = 20)
	public String getVoterIdNo() {
		return this.voterIdNo;
	}

	public void setVoterIdNo(String voterIdNo) {
		this.voterIdNo = voterIdNo;
	}

	@Column(name = "VOTER_ID_IMG", length = 250)
	public String getVoterIdImg() {
		return this.voterIdImg;
	}

	public void setVoterIdImg(String voterIdImg) {
		this.voterIdImg = voterIdImg;
	}

	@Column(name = "ADHAR_CARD_NO", nullable = false, length = 20)
	public String getAdharCardNo() {
		return this.adharCardNo;
	}

	public void setAdharCardNo(String adharCardNo) {
		this.adharCardNo = adharCardNo;
	}

	@Column(name = "ADHAR_CARD_IMG", length = 80)
	public String getAdharCardImg() {
		return this.adharCardImg;
	}

	public void setAdharCardImg(String adharCardImg) {
		this.adharCardImg = adharCardImg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_JOINING", length = 19)
	public Date getDateOfJoining() {
		return this.dateOfJoining;
	}

	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}

	@Column(name = "PERMANENT_ADDR1", length = 80)
	public String getPermanentAddr1() {
		return this.permanentAddr1;
	}

	public void setPermanentAddr1(String permanentAddr1) {
		this.permanentAddr1 = permanentAddr1;
	}

	@Column(name = "PERMANENT_ADDR2", length = 80)
	public String getPermanentAddr2() {
		return this.permanentAddr2;
	}

	public void setPermanentAddr2(String permanentAddr2) {
		this.permanentAddr2 = permanentAddr2;
	}

	@Column(name = "PERMANENT_ADDR3", length = 80)
	public String getPermanentAddr3() {
		return this.permanentAddr3;
	}

	public void setPermanentAddr3(String permanentAddr3) {
		this.permanentAddr3 = permanentAddr3;
	}

	@Column(name = "PRESENT_ADDR1", length = 80)
	public String getPresentAddr1() {
		return this.presentAddr1;
	}

	public void setPresentAddr1(String presentAddr1) {
		this.presentAddr1 = presentAddr1;
	}

	@Column(name = "PRESENT_ADDR2", length = 80)
	public String getPresentAddr2() {
		return this.presentAddr2;
	}

	public void setPresentAddr2(String presentAddr2) {
		this.presentAddr2 = presentAddr2;
	}

	@Column(name = "PRESENT_ADDR3", length = 80)
	public String getPresentAddr3() {
		return this.presentAddr3;
	}

	public void setPresentAddr3(String presentAddr3) {
		this.presentAddr3 = presentAddr3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_TIME", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "STATUS", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rrUserProfile")
	public Set<RrOrder> getRrOrders() {
		return this.rrOrders;
	}

	public void setRrOrders(Set<RrOrder> rrOrders) {
		this.rrOrders = rrOrders;
	}

}
